export const DARK_MODE = 'darkMode'
export const ADD_LOCATION = 'addLocation'
export const DELETE_LOCATION = 'deleteLocation'
export const UPDATE_LOCATION = 'updateLocation'
export const GET_CITY_CURRENT_WEATHER = 'getCityCurrentWeather'
